# Generated by Django 4.1 on 2022-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="a", max_length=100, verbose_name="First Name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="b", max_length=100, verbose_name="Last Name"
            ),
            preserve_default=False,
        ),
    ]
