# Generated by Django 4.1 on 2022-08-21 15:16

from django.db import migrations, models
import portfolio.models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="institution_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.Education.directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.Experience.directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.Project.directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.ProjectImage.directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.Skill.directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.Testimonial.directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.Testimonial.video_directory_path,
            ),
        ),
    ]
