# Generated by Django 4.1 on 2022-08-22 10:29

from django.db import migrations, models
import portfolio.models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="about", name="cv_link",),
        migrations.AddField(
            model_name="about",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.ftp.FTPStorage(),
                upload_to=portfolio.models.About.directory_path,
            ),
        ),
    ]
