# Generated by Django 4.1 on 2022-08-22 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0005_remove_about_cv_link_about_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="displayName",
            field=models.CharField(default="k", max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="professions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.profession",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
