# Generated by Django 4.1 on 2022-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_about_displayname_about_professions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="aboutYourself",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
