# Generated by Django 4.1 on 2022-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("active", models.BooleanField(default=False)),
                (
                    "host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text='default host is "smtp.gmail.com". if you want to change it then give your host, otherwise leave it ',
                        max_length=50,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=587,
                        help_text='default port is "587". if you want to change it then give your port no, otherwise leave it',
                    ),
                ),
                ("tls", models.BooleanField(default=False)),
                ("ssl", models.BooleanField(default=False)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        help_text="<p><b>For Gmail: You need to follow those steps:</b></p><br><p>1. Enable less secure app for your gmail from this link https://myaccount.google.com/lesssecureapps </p> <br><p>2. Enable 2-Step Verification from your gmail account.</p> <br><p>3. Generate an App passwords from your gmail account and upload here. https://myaccount.google.com/apppasswords</p> <br>",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
