# Generated by Django 4.1 on 2022-08-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinfo",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="mailinfo",
            name="subject",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Title"
            ),
        ),
    ]
